<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-EUDIV0F" name="PetStoreTest" tests="36" failures="25" timestamp="11 Sep 2022 20:38:22 GMT" time="4.529" errors="0">
  <testcase name="test_AddUserWithLongFieldValues" time="0.28" classname="com.petStore.test.fuctional.CreateUserWithArrayFunctionalTest">
    <failure type="java.lang.AssertionError" message="Actual Response Code should be 400 instead od success as payload has long field names and is client error: expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: Actual Response Code should be 400 instead od success as payload has long field names and is client error: expected [400] but found [200]
	at com.petStore.test.fuctional.CreateUserWithArrayFunctionalTest.test_AddUserWithLongFieldValues(CreateUserWithArrayFunctionalTest.java:158)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_AddUserWithLongFieldValues -->
  <testcase name="test_addSingleUserWithInvalidPhoneNo" time="0.266" classname="com.petStore.test.fuctional.CreateUserWithArrayFunctionalTest">
    <failure type="java.lang.AssertionError" message="Actual Response Code should be 400 as payload has invalid phone and is client error :  expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: Actual Response Code should be 400 as payload has invalid phone and is client error :  expected [400] but found [200]
	at com.petStore.test.fuctional.CreateUserWithArrayFunctionalTest.test_addSingleUserWithInvalidPhoneNo(CreateUserWithArrayFunctionalTest.java:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_addSingleUserWithInvalidPhoneNo -->
  <testcase name="test_addSingleUserWithInValidEmailPattern" time="0.743" classname="com.petStore.test.fuctional.CreateUserWithArrayFunctionalTest">
    <failure type="java.lang.AssertionError" message="Actual Response Code should be 400 as payload has invalid emailpattern and is client error: expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: Actual Response Code should be 400 as payload has invalid emailpattern and is client error: expected [400] but found [200]
	at com.petStore.test.fuctional.CreateUserWithArrayFunctionalTest.test_addSingleUserWithInValidEmailPattern(CreateUserWithArrayFunctionalTest.java:190)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_addSingleUserWithInValidEmailPattern -->
  <testcase name="test_creatPetWithInValidPhotoUrls" time="0.76" classname="com.petStore.test.fuctional.CreatePetFunctionalTest">
    <failure type="java.lang.AssertionError" message="The processing should fail with actual Response Code 400 as payload has invlid photourls and is client error:  expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: The processing should fail with actual Response Code 400 as payload has invlid photourls and is client error:  expected [400] but found [200]
	at com.petStore.test.fuctional.CreatePetFunctionalTest.test_creatPetWithInValidPhotoUrls(CreatePetFunctionalTest.java:135)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_creatPetWithInValidPhotoUrls -->
  <testcase name="test_addMultipleUser" time="0.766" classname="com.petStore.test.fuctional.CreateUserWithArrayFunctionalTest"/>
  <testcase name="test_creatPetWithInvalidPetIdPattern" time="0.796" classname="com.petStore.test.fuctional.CreatePetFunctionalTest"/>
  <testcase name="test_creatPetWithLongFieldNames" time="0.802" classname="com.petStore.test.fuctional.CreatePetFunctionalTest">
    <failure type="java.lang.AssertionError" message="The processing should fail with actual Response Code 400 as payload has long field values and is client error:  expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: The processing should fail with actual Response Code 400 as payload has long field values and is client error:  expected [400] but found [200]
	at com.petStore.test.fuctional.CreatePetFunctionalTest.test_creatPetWithLongFieldNames(CreatePetFunctionalTest.java:177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_creatPetWithLongFieldNames -->
  <testcase name="test_creatPetWithValidFields" time="0.808" classname="com.petStore.test.fuctional.CreatePetFunctionalTest"/>
  <testcase name="test_addSingleUserWithinvalidId" time="0.27" classname="com.petStore.test.fuctional.CreateUserWithArrayFunctionalTest">
    <failure type="java.lang.AssertionError" message="Actual Response Code should be 400 as payload has invalid userId and is client error: expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: Actual Response Code should be 400 as payload has invalid userId and is client error: expected [400] but found [500]
	at com.petStore.test.fuctional.CreateUserWithArrayFunctionalTest.test_addSingleUserWithinvalidId(CreateUserWithArrayFunctionalTest.java:561)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_addSingleUserWithinvalidId -->
  <testcase name="test_addSinglleuserWihtInvalidUserStatus" time="0.26" classname="com.petStore.test.fuctional.CreateUserWithArrayFunctionalTest">
    <failure type="java.lang.AssertionError" message="The processing should fail with actual Response Code 400 as payload has invalid userstatus and is client error expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: The processing should fail with actual Response Code 400 as payload has invalid userstatus and is client error expected [400] but found [200]
	at com.petStore.test.fuctional.CreateUserWithArrayFunctionalTest.test_addSinglleuserWihtInvalidUserStatus(CreateUserWithArrayFunctionalTest.java:594)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_addSinglleuserWihtInvalidUserStatus -->
  <testcase name="test_getUserforDuplicateRecords" time="0.263" classname="com.petStore.test.fuctional.GetUserByNameFunctionalTest">
    <failure type="org.springframework.web.client.HttpClientErrorException$NotFound" message="404 Not Found">
      <![CDATA[org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:85)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:102)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670)
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:338)
	at com.petStore.test.fuctional.GetUserByNameFunctionalTest.test_getUserforDuplicateRecords(GetUserByNameFunctionalTest.java:198)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- test_getUserforDuplicateRecords -->
  <testcase name="test_updatePetWithInValidStatus" time="0.266" classname="com.petStore.test.fuctional.UpdatePetFunctionalTest">
    <failure type="java.lang.AssertionError" message="The processing should fail with actual Response Code 400 instead of success as payload has invalid status and is client error:  expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: The processing should fail with actual Response Code 400 instead of success as payload has invalid status and is client error:  expected [400] but found [200]
	at com.petStore.test.fuctional.UpdatePetFunctionalTest.test_updatePetWithInValidStatus(UpdatePetFunctionalTest.java:182)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_updatePetWithInValidStatus -->
  <testcase name="test_updatePetWithInvalidIdsPattern" time="0.245" classname="com.petStore.test.fuctional.UpdatePetFunctionalTest">
    <failure type="java.lang.AssertionError" message="The processing  failure  Response Code should be 400 as payload has invalidIds and is client error:  expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: The processing  failure  Response Code should be 400 as payload has invalidIds and is client error:  expected [400] but found [500]
	at com.petStore.test.fuctional.UpdatePetFunctionalTest.test_updatePetWithInvalidIdsPattern(UpdatePetFunctionalTest.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_updatePetWithInvalidIdsPattern -->
  <testcase name="test_getUserByUpdatedName" time="0.537" classname="com.petStore.test.fuctional.GetUserByNameFunctionalTest"/>
  <testcase name="test_updatePetWithValidFields" time="0.257" classname="com.petStore.test.fuctional.UpdatePetFunctionalTest"/>
  <testcase name="test_updatePetWithLongFieldNames" time="0.284" classname="com.petStore.test.fuctional.UpdatePetFunctionalTest">
    <failure type="java.lang.AssertionError" message="Actual Response Code should be 400 as payload has long Field  names and is client error: expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: Actual Response Code should be 400 as payload has long Field  names and is client error: expected [400] but found [200]
	at com.petStore.test.fuctional.UpdatePetFunctionalTest.test_updatePetWithLongFieldNames(UpdatePetFunctionalTest.java:275)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_updatePetWithLongFieldNames -->
  <testcase name="test_addOneUser" time="1.753" classname="com.petStore.test.fuctional.CreateUserWithArrayFunctionalTest"/>
  <testcase name="test_creatPetWithInValidStatus" time="1.76" classname="com.petStore.test.fuctional.CreatePetFunctionalTest">
    <failure type="java.lang.AssertionError" message="The processing should fail with actual Response Code 400 as payload has invlid status enum values and is client error:  expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: The processing should fail with actual Response Code 400 as payload has invlid status enum values and is client error:  expected [400] but found [200]
	at com.petStore.test.fuctional.CreatePetFunctionalTest.test_creatPetWithInValidStatus(CreatePetFunctionalTest.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_creatPetWithInValidStatus -->
  <testcase name="test_getPetsBasedOnFieldStatusPending" time="0.259" classname="com.petStore.test.fuctional.GetPetBasedOnStatusFuctionalTest"/>
  <testcase name="test_updateUseWithinvalidUserStatus" time="0.276" classname="com.petStore.test.fuctional.UpdateUserFunctionalTest">
    <failure type="java.lang.AssertionError" message="Actual Response Code should be 400 as payload has invaldUserStatus Pattern and is client error: expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: Actual Response Code should be 400 as payload has invaldUserStatus Pattern and is client error: expected [400] but found [200]
	at com.petStore.test.fuctional.UpdateUserFunctionalTest.test_updateUseWithinvalidUserStatus(UpdateUserFunctionalTest.java:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_updateUseWithinvalidUserStatus -->
  <testcase name="test_updateUserWithinvalidPhonePattern" time="0.275" classname="com.petStore.test.fuctional.UpdateUserFunctionalTest">
    <failure type="java.lang.AssertionError" message="Actual Response Code should be 400 as payload has invaldPhone Pattern and is client error: expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: Actual Response Code should be 400 as payload has invaldPhone Pattern and is client error: expected [400] but found [200]
	at com.petStore.test.fuctional.UpdateUserFunctionalTest.test_updateUserWithinvalidPhonePattern(UpdateUserFunctionalTest.java:248)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_updateUserWithinvalidPhonePattern -->
  <testcase name="test_updateUserWithLongfieldNames" time="0.273" classname="com.petStore.test.fuctional.UpdateUserFunctionalTest">
    <failure type="java.lang.AssertionError" message="Actual Response Code should be 400 as payload has verylong usernameupdate and is client error: expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: Actual Response Code should be 400 as payload has verylong usernameupdate and is client error: expected [400] but found [200]
	at com.petStore.test.fuctional.UpdateUserFunctionalTest.test_updateUserWithLongfieldNames(UpdateUserFunctionalTest.java:180)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_updateUserWithLongfieldNames -->
  <testcase name="test_getPetsBasedOnFieldStatusAvailableWithsqlInjection" time="0.081" classname="com.petStore.test.nonfuctional.GetPetBasedOnStatusNonFunctional">
    <failure type="org.springframework.web.client.ResourceAccessException" message="I/O error on GET request for &amp;quot;https://petstore.swagger.iov2/pet/findByStatus&amp;quot;: petstore.swagger.iov2; nested exception is java.net.UnknownHostException: petstore.swagger.iov2">
      <![CDATA[org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://petstore.swagger.iov2/pet/findByStatus": petstore.swagger.iov2; nested exception is java.net.UnknownHostException: petstore.swagger.iov2
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:744)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670)
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:338)
	at com.petStore.test.nonfuctional.GetPetBasedOnStatusNonFunctional.test_getPetsBasedOnFieldStatusAvailableWithsqlInjection(GetPetBasedOnStatusNonFunctional.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.net.UnknownHostException: petstore.swagger.iov2
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:196)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:162)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
	at java.net.Socket.connect(Socket.java:606)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:298)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:292)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:395)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1167)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1061)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:76)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:735)
	... 16 more
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- test_getPetsBasedOnFieldStatusAvailableWithsqlInjection -->
  <testcase name="test_BulkUserCreation" time="2.008" classname="com.petStore.test.fuctional.CreateUserWithArrayFunctionalTest">
    <failure type="java.lang.AssertionError" message="Actual Response Code should be 413 as payload is too large and is client error : expected [413] but found [500]">
      <![CDATA[java.lang.AssertionError: Actual Response Code should be 413 as payload is too large and is client error : expected [413] but found [500]
	at com.petStore.test.fuctional.CreateUserWithArrayFunctionalTest.test_BulkUserCreation(CreateUserWithArrayFunctionalTest.java:484)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_BulkUserCreation -->
  <testcase name="test_creatPetWithImproperJsonFormat" time="0.258" classname="com.petStore.test.nonfuctional.CreatePetNonFunctional">
    <failure type="java.lang.AssertionError" message="Processing should fail with Error Code 400 as Payload has as invalid comma in tag array : expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: Processing should fail with Error Code 400 as Payload has as invalid comma in tag array : expected [400] but found [500]
	at com.petStore.test.nonfuctional.CreatePetNonFunctional.test_creatPetWithImproperJsonFormat(CreatePetNonFunctional.java:141)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_creatPetWithImproperJsonFormat -->
  <testcase name="test_creatPetWithNonExixtentFieldNameandValue" time="0.269" classname="com.petStore.test.nonfuctional.CreatePetNonFunctional">
    <failure type="java.lang.AssertionError" message="Processing should fail with Error Code 400 rather than success as invalid field shoudld throw schema validation error : expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: Processing should fail with Error Code 400 rather than success as invalid field shoudld throw schema validation error : expected [400] but found [200]
	at com.petStore.test.nonfuctional.CreatePetNonFunctional.test_creatPetWithNonExixtentFieldNameandValue(CreatePetNonFunctional.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_creatPetWithNonExixtentFieldNameandValue -->
  <testcase name="test_createSingleUserWithMoreThanMaxIdSuported" time="0.257" classname="com.petStore.test.nonfuctional.CreateUserWithArrayNonFunctinal">
    <failure type="java.lang.AssertionError" message="Actual Response Code should be 400 as payload has invalid Id more than Integer.Max and is client error: expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: Actual Response Code should be 400 as payload has invalid Id more than Integer.Max and is client error: expected [400] but found [500]
	at com.petStore.test.nonfuctional.CreateUserWithArrayNonFunctinal.test_createSingleUserWithMoreThanMaxIdSuported(CreateUserWithArrayNonFunctinal.java:94)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_createSingleUserWithMoreThanMaxIdSuported -->
  <testcase name="test_createSingleUserWithInvalidPayloadFormat" time="0.267" classname="com.petStore.test.nonfuctional.CreateUserWithArrayNonFunctinal">
    <failure type="java.lang.AssertionError" message="Actual Response Code should be 400 with schema validation error as it has comma after array: expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: Actual Response Code should be 400 with schema validation error as it has comma after array: expected [400] but found [500]
	at com.petStore.test.nonfuctional.CreateUserWithArrayNonFunctinal.test_createSingleUserWithInvalidPayloadFormat(CreateUserWithArrayNonFunctinal.java:137)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_createSingleUserWithInvalidPayloadFormat -->
  <testcase name="test_getUserForNonExistentUserName" time="0.266" classname="com.petStore.test.nonfuctional.GetUserByNameNonFucntional"/>
  <testcase name="test_updateUsewithValidValues" time="0.492" classname="com.petStore.test.fuctional.UpdateUserFunctionalTest"/>
  <testcase name="test_getUserForNonExistentUserNameWithSqlInjection" time="0.246" classname="com.petStore.test.nonfuctional.GetUserByNameNonFucntional">
    <failure type="java.lang.AssertionError" message="Processing should fail with Error Code 400 as Payload rather than processing giving 404 not found search result as we had sql injection in query paramaters : expected [400] but found [404]">
      <![CDATA[java.lang.AssertionError: Processing should fail with Error Code 400 as Payload rather than processing giving 404 not found search result as we had sql injection in query paramaters : expected [400] but found [404]
	at com.petStore.test.nonfuctional.GetUserByNameNonFucntional.test_getUserForNonExistentUserNameWithSqlInjection(GetUserByNameNonFucntional.java:95)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_getUserForNonExistentUserNameWithSqlInjection -->
  <testcase name="test_updateUserWithinvalidEmailPattern" time="0.731" classname="com.petStore.test.fuctional.UpdateUserFunctionalTest">
    <failure type="java.lang.AssertionError" message="Actual Response Code should be 400 as payload has invaldemail Pattern and is client error: expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: Actual Response Code should be 400 as payload has invaldemail Pattern and is client error: expected [400] but found [200]
	at com.petStore.test.fuctional.UpdateUserFunctionalTest.test_updateUserWithinvalidEmailPattern(UpdateUserFunctionalTest.java:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_updateUserWithinvalidEmailPattern -->
  <testcase name="test_getPetsBasedOnFieldStatusSold" time="0.744" classname="com.petStore.test.fuctional.GetPetBasedOnStatusFuctionalTest"/>
  <testcase name="test_updateUserWithNonExistingUserName" time="0.283" classname="com.petStore.test.nonfuctional.UpdateUserNonFunctional">
    <failure type="java.lang.AssertionError" message="Processing should fail with 404 instead of success as we are trying to update nonexistent object  : expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: Processing should fail with 404 instead of success as we are trying to update nonexistent object  : expected [404] but found [200]
	at com.petStore.test.nonfuctional.UpdateUserNonFunctional.test_updateUserWithNonExistingUserName(UpdateUserNonFunctional.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_updateUserWithNonExistingUserName -->
  <testcase name="test_getPetsBasedOnFieldStatusAvailable" time="0.825" classname="com.petStore.test.fuctional.GetPetBasedOnStatusFuctionalTest"/>
  <testcase name="test_updateNonExistencePet" time="0.494" classname="com.petStore.test.nonfuctional.UpdatePetStatusNonFunctional">
    <failure type="java.lang.AssertionError" message="Processing should fail with Error Code 404 as Payload has an non existent object : expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: Processing should fail with Error Code 404 as Payload has an non existent object : expected [404] but found [200]
	at com.petStore.test.nonfuctional.UpdatePetStatusNonFunctional.test_updateNonExistencePet(UpdatePetStatusNonFunctional.java:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_updateNonExistencePet -->
</testsuite> <!-- PetStoreTest -->
